{% if needs_java %}
FROM anapsix/alpine-java:jre8
{% else %}
FROM alpine:3.3
{% endif %}

MAINTAINER {{ name }} <{{ email }}>

ARG git_repository="Unknown"
ARG git_commit="Unknown"
ARG git_branch="Unknown"
ARG built_on="Unknown"

{% if needs_entrypoint %}
ENTRYPOINT ["/sbin/tini", "--", "/docker-entrypoint.sh"]
COPY ./docker-entrypoint.sh /docker-entrypoint.sh
{% else %}
ENTRYPOINT ["/sbin/tini", "--"]
{% endif %}

CMD {{ docker_cmd }}

COPY ./Dockerfile /Dockerfile

{% if port is number %}
EXPOSE {{ port }}
{% endif %}

RUN apk add --update --repository https://dl-cdn.alpinelinux.org/alpine/edge/community/ tini=0.9.0-r1 {{ deps }}

LABEL git.repository=$git_repository
LABEL git.commit=$git_commit
LABEL git.branch=$git_branch
LABEL build.dockerfile=/Dockerfile
LABEL build.on=$built_on

WORKDIR /code

COPY {{ src }} /code/

{% if app_deps %}
RUN {{ app_deps }}
{% endif %}