{% if needs_java %}
FROM anapsix/alpine-java:jre8
{% else %}
FROM alpine:3.3
{% endif %}

MAINTAINER {{ name }} <{{ email }}>

ARG vcs_type="Unknown"
ARG vcs_url="Unknown"
ARG vcs_ref="Unknown"
ARG vcs_branch="Unknown"
ARG build_date="Unknown"

{% if needs_entrypoint %}
ENTRYPOINT ["/sbin/tini", "--", "/docker-entrypoint.sh"]
COPY ./docker-entrypoint.sh /docker-entrypoint.sh
{% else %}
ENTRYPOINT ["/sbin/tini", "--"]
{% endif %}

CMD {{ docker_cmd }}

COPY ./Dockerfile /Dockerfile

{% if port is number %}
EXPOSE {{ port }}
{% endif %}

RUN apk add --update --repository https://dl-cdn.alpinelinux.org/alpine/edge/community/ tini=0.9.0-r1 {{ deps }}

LABEL org.label-schema.vcs-type=$vcs_type \
      org.label-schema.vcs-url=$vcs_url \
      org.label-schema.vcs-ref=$vcs_ref \
      org.label-schema.vcs-branch=$vcs_branch \
      org.label-schema.docker.dockerfile=/Dockerfile \
      org.label-schema.build-date=$build_date

WORKDIR /code

COPY {{ src }} /code/

{% if app_deps %}
RUN {{ app_deps }}
{% endif %}